name: Build CatBot Only

on: workflow_dispatch

jobs:
  build-catbot-only:
    name: Build CatBot only
    runs-on: windows-latest

    env:
      SolutionName: CatBot.sln
      Architecture: x86
      DotNetVersion: net9.0-windows10.0.22000.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        
      - name: Restore the application
        run: msbuild $env:SolutionName /t:Restore /p:Configuration=Release

      - name: Restore NuGet Packages
        run: nuget restore $env:SolutionName

      - name: Build solution
        run: msbuild $env:SolutionName /t:rebuild /p:Configuration=Release
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CatBot
          path: bin/${{ env.Architecture }}/Release/${{ env.DotNetVersion }}
